### ISSUE TITLE
LM landing gear deployment causes RCS plume to become displaced

### ISSUE THREAD

**Issue by ThatRedMelon** [dseagrav/NASSP#1016]
During LM activation, after the landing gear has been deployed, the RCS plume becomes displaced vertically downwards, and stays there until the simulator is reloaded (as seen in the image below during a +X thruster firing).
![image](https://github.com/orbiternassp/NASSP/assets/34657891/7fd1b966-5c3d-4afb-8c31-9bf8f1a948af)

**Comment by indy91** [comment]
Fixed in #1048
