### ISSUE TITLE
ABORT light in CM should be red, not yellow

### ISSUE THREAD

**Issue by rcflyinghokie** [dseagrav/NASSP#1099]
![image](https://github.com/orbiternassp/NASSP/assets/22916885/09c9665e-a6da-4516-8254-2fe27649487b)
![image](https://github.com/orbiternassp/NASSP/assets/22916885/34cba4b7-384a-4140-8d0a-a70b42c6bed5)

**Comment by Jordan-64** [comment]
Does this only apply to the 2D view? I didn't find a yellow ABORT texture for the VC.
