### ISSUE TITLE
Rocket won't show up on OpenOrbiter

### ISSUE THREAD

**Issue by TheSystemGuy1337** [dseagrav/NASSP#1277]
Self explanatory. Read the instructions by the letter and I was rewarded with this:

![image](https://github.com/user-attachments/assets/b878bc9e-ae70-4a52-bf64-27c76d0d8934)

Attempting to start at 30 seconds to launch presents this:

![image](https://github.com/user-attachments/assets/3d0f77fb-f7ae-4828-ad26-d8a5aff09e7a)

I tried looking for any information about this, and found nothing. What the heck is even going on?

[Orbiter.log](https://github.com/user-attachments/files/16321750/Orbiter.log)

**Comment by CaptainSwag101** [comment]
Hello, what instructions were you following specifically? NASSP doesn't support OpenOrbiter; our official installation guide provides a link to Orbiter Beta R90. I have my own custom branch which focuses on OpenOrbiter support but it's not ready for wide use at this time.

**Comment by TheSystemGuy1337** [comment]
I was following these: https://nassp.space/index.php/Installation

Since it doesn't support OpenOrbiter, I will try using Beta R90

**Comment by CaptainSwag101** [comment]
Check out these instructions, they might go into better detail as well: [https://www.orbiter-forum.com/threads/nassp-8-installation-guide.36801/](https://www.orbiter-forum.com/threads/nassp-8-installation-guide.36801/). If you're savvy enough to build NASSP from source it is possible to use OpenOrbiter, but it's a decent amount of extra work and it's not as fully-tested. My eventual goal is to make it possible to use NASSP with either version of Orbiter, but that's a ways off still.

**Comment by TheSystemGuy1337** [comment]
Rocket finally showed up for work. Couldn't use D3D9 otherwise it would C2D. Now, how do I access the 3D Virtual Cockpit, if it even has one? Also, my FDAIS/8-balls/artifical horizons won't move

![image](https://github.com/user-attachments/assets/4c8166f6-1b25-4074-894d-b2a0e66ca2ff)

**Comment by rcflyinghokie** [comment]
I think you got all this sorted in discord, correct?

**Comment by CaptainSwag101** [comment]
Yes, all sorted out. Closing this now.
