### ISSUE TITLE
Terrain at the launch pads in Orbiter 2016 is not precisely flat

### ISSUE THREAD

**Issue by indy91** [dseagrav/NASSP#180]
Due to the terrain introduced in Orbiter 2016, the launchpads used in NASSP (mainly LC-39 and LC-34) are not 100% flat. This has a bad effect on the prelaunch alignment of the IMU in the Instrument Unit. While launches from LC-39A only get a slightly higher orbital insertion error due to this, the misalignment on LC-34 is much more severe and effectively break Apollo 7 launches at the moment. To fix this issue the elevation maps of Orbiter 2016 have to be edited.

**Comment by jalexb88** [comment]
I have completed my work on the elevation files for LC34 and LC39A/B. All that is needed now is a bit of testing and I think we can call this one done.
