### ISSUE TITLE
P52 and Separation swapped in A7

### ISSUE THREAD

**Issue by Thymo-** [dseagrav/NASSP#19]
Whilst doing the Apollo 7 mission I noticed that the Separation and P52 were swapped around in the flightplan. Attached is the correct version (In xlsx because Github doesn't allow xls).

[Apollo 7 Flightplan vAGC.xlsx](https://github.com/dseagrav/NASSP/files/232921/Apollo.7.Flightplan.vAGC.xlsx)

**Comment by indy91** [comment]
Thank you. The flight plan is a little bit confusing in that regard, the P52 actually appears in the Separation part of the checklist, too. I'll have to talk with Pattersoncr about it, but I think the goal is to replace the Excel flight plans with Word or PDFs that look closer to the original NASA checklists and have the Checklist MFD act as the step-by-step "tutorial". The most recent update for the Apollo 7 word documents can be found here: http://www.ibiblio.org/mscorbit/mscforum/index.php?topic=2863.msg23321#msg23321 They are WIP though and can't really be finalized until it is clear what systems and features will be in a 7.0 release.

**Comment by indy91** [comment]
The Excel checklist for Apollo 7 has now been replaced by a (stil work-in-progress) word checklist, which doesn't have this issue.
