### ISSUE TITLE
Waste dump offset

### ISSUE THREAD

**Issue by Thymo-** [dseagrav/NASSP#21]
When trying to dump the waste water the drains appear to be offset in front of the CSM when looking out the rendezvous window. See attached picture below.

![image](https://cloud.githubusercontent.com/assets/7950685/14796287/dbf3c672-0b2c-11e6-9483-38d6c83ec681.png)

**Comment by indy91** [comment]
Just had a look at this. Weird, I can't reproduce this issue. What version of NASSP were you using and what resolution did your screen have in this picture?

**Comment by Thymo-** [comment]
I was using the latest build from git at the time. Running at 1920x1080.

**Comment by indy91** [comment]
I still have trouble reproducing it, do you maybe have a scenario with the issue occuring?

**Comment by Thymo-** [comment]
This one has it. But I have found it to be not scenario specific.
You can see it out of window 2.
[dump_offset.scn.txt](https://github.com/dseagrav/NASSP/files/333356/dump_offset.scn.txt)

**Comment by indy91** [comment]
At first I still couldn't replicate it, but then I tried it with my old, clean NASSP installation and there it was. It appears to be an issue with an older version of the D3D9 Client. Which version are you using? It still occurs with R15, but with the most recent release (R16.4 I think: http://orbiter-forum.com/showthread.php?p=530083&postcount=3618) the problem disappeared. Does this solve the problem?

**Comment by Thymo-** [comment]
I'm currently on the latest stable version (R15 indeed).

Is this the only place this version is available from? Otherwise I'll have to create another account on a site I probably won't visit for a long time.

**Comment by indy91** [comment]
Ah right, you need an account to download from the Orbiter Forum. The D3D9 client developers don't use the codeplex page anymore for updates, so the only alternative I found is here: http://www.tuttovola.org/index.php?action=downloads;sa=view;down=1134 for R16.5. I've never seen that website before, but it appears to have a forum with Italian Orbiter Forum regulars running it and the file size is exactly the same, so I would trust it.

**Comment by Thymo-** [comment]
I'll just use the first one. Maybe we should include it in the repo or forums? It's distributed under  GPLv3 (Not entirely sure we can since we're using v2).

**Comment by indy91** [comment]
No idea about this license stuff. At the very least the NASSP installation instructions should be updated. This latest D3D9 Client version for Orbiter 2010 should really be more accessible, I'll ask the devs about it.
