### ISSUE TITLE
ICDU Zero procedure coarse aligns IMU to zero

### ISSUE THREAD

**Issue by indy91** [dseagrav/NASSP#28]
The procedure to zero the ICDU counters (Verb 40 in the AGC) also sets the IMU gimbal angles to zero and changes the attitude reference. This is not the intended behavior of the CDUs. In NASSP the CDU counters are not separately simulated at the moment, so the IMU gimbal angles and CDU "angles" are always identical.

A proper implementation would separate the digital counters and analog IMU readings. The method "DoZeroIMUCDUs()" in the IMU class is also often used, when a coarse alignment to zero is intended. This has to be changed as well.

**Comment by rcflyinghokie** [comment]
I think this has been fixed?

**Comment by indy91** [comment]
Yeah, you are right. It's just a preliminary solution for now, but ICDU Zero doesn't cause a coarse alignment anymore. So in that sense it has been fixed.
