### ISSUE TITLE
Can this addon be used to go to mars?

### ISSUE THREAD

**Issue by hydrogenpi** [dseagrav/NASSP#301]
or is it strictly limited to the moon? 

I know I would need to edit a few parameters like fuel level and whatnot... but in theory is the tech on board the LM/CSM enough to do a flight to mars or for example alpha centari?

**Comment by dseagrav** [comment]
Mars would be a lot of work. In real life, the LM would not survive descent into any atmosphere. It was designed to operate in a vacuum only. It would require extensive redesign to include the heat shielding and such necessary. On top of that, the flight software in the various computers would need extensive updating to have the data tables needed to operate outside the earth/moon system, assuming it even can.

Alpha Centauri is out of the question.

**Comment by hydrogenpi** [comment]
Okay thanks for the answer. It just seem like if it wasn't manned, the Voyager 1 and 2 have made it close to Alpha Centauri so I figured it was matter of distance/time which in Orbiter can use exteme time compression since even the helisophere isn't simulated.

**Comment by dseagrav** [comment]
I suggest you look into AMSO instead. We use the original NASA flight software and therefore have all of its assumptions and constraints, and it does not handle high time compression very well at all, let alone the extreme compression needed for such a trip.

**Comment by Thymo-** [comment]
In the future it may be possible. We do have plans to eventually implement AAP missions, one of them to Venus.
Of course that will require custom software for the AGC, which is being worked on (ever so slowly).
