### ISSUE TITLE
Rotary switches should cycle through sequentially, not to the clicked position.

### ISSUE THREAD

**Issue by rcflyinghokie** [dseagrav/NASSP#315]
Rotary switches in the LM (and the CM, just change the behavior of the class) should be changed so that the new position does not snap to the position clicked, but rather through all positions until the desired position is reached, similar to that of a three position switch.  While this was convenient, it messes with checklist flows which plan for and anticipate cycling through other positions to get to the desired one.  

For example, in the LM glycol pump test, a comp light is expected when cycling from SEC to Pump 2, however since clicking Pump 2 makes the switch select it right away, you do not get the expected results.

**Comment by Thymo-** [comment]
Some code should already account for this (EMS) by cycling through the positions internally.
Maybe this can be propagated to the systems not doing this as a less invasive approach.
