### ISSUE TITLE
Assertion failed in D3D9surface.cpp  at Line 843 when going down to LEB

### ISSUE THREAD

**Issue by ggalfi** [dseagrav/NASSP#338]
Hi all,

Using the actual Orbiter2016 branch I get the following error followed by CTD when I try to go down to LEB:
![image](https://user-images.githubusercontent.com/33571169/38454263-fba287d4-3a63-11e8-9598-4588953326e0.png)
Seem to me the problem caused by a 30. Mar change in the saturnpanel.cpp (commit 7a5c7e4), in which the CSM MFD-s (4 in the LEB) were resized. The two MFDs under the main panel are fine anyway. 

Reverting the changes in the saturnpanel.cpp solved this problem for me, so I suggest doing something similar in the active branch as well.

Cheers,
Gergely

**Comment by indy91** [comment]
That's a good bug report, I think jalexb88 will know how to fix this. Thanks!

**Comment by indy91** [comment]
#339 probably fixed this issue. Can you confirm that?

**Comment by jalexb88** [comment]
OK, so I have noticed that it the case where split panels are used in the CSM LEB, the left most of the 4 MFDs went off the left border of the middle LEB panel. So I shifted the MFDs to the right by a few pixels and that mkaes them display correctly. ggalfi, I have made a pull request to the main repo, and once its merged and the auto build complete, you can download the updated alpha release (or rebuild yourself). Let me know if that fixes it!
