### ISSUE TITLE
Late Contact Signal

### ISSUE THREAD

**Issue by ggalfi** [dseagrav/NASSP#362]
Hi all,

when I do a lunar landing with the current version, the Contact Light comes up only when the footpads are touching the lunar surface. But it supposed to light up a few seconds earlier when only the probes have  contacted with the ground. I've tried to figure out how this contact thing is handled and I've seen that the contact signal is practically  based on the touchdown points specified in the function SetLmVesselHoverStage and these td points are only defined for the  level of the footpads or above (there is some obscure code with other td points which refers to the CollisionSDK however I see no sign that these are ever taken into account during the creation of the contact signal). So first of all I simply added three new td points corresponding to the ends of the probes. To avoid the funny situation when the LM standing on the tip of the probes I reduced the stiffness and damping by a factor of 100 for these three new probes. Additionally I changed the number and the arrangement of the original td points to model more accurately the real layout of the footpads. Surprisingly this gives a much simpler set of touchdown points as the footpads are simply the four corners of a square rotated by 45 degrees.  I tested my changes and now I can do the same free-fall touchdowns as you can see on the real Apollo videos. Also the LM sits firmly on it's footpads after touching down even on  slopy terrain. I attached my version of lemmesh.cpp. You may incorporate the changes into the main branch if you are happy with these  corrections.

Cheers

[lemmesh.zip](https://github.com/dseagrav/NASSP/files/2100357/lemmesh.zip)

**Comment by indy91** [comment]
Yeah, the current logic for the lights is using the ground contact function from the Orbiter API, so whatever is defined as the touchdown points, determines if the lights can be on or not.

The obscure code for the CollisionSDK is just some unused, outdated code I believe. Should probably be removed, although I believe there was some difficulty with removing it entirely. This was before my time working on NASSP, but I believe the CollisionSDK was used to make the LM interact with lunar landing site meshes, that where part of NASSP before Orbiter 2016 introduced terrain properly. Not quite sure actually.

I'll definitely take a look at how these touchdown points behave. I know what we had a lot of trouble with all of the vehicles (LM, Saturn etc.) getting the touchdown points right, so that they are stable, standing straight up and don't fall over. If the TD points you worked out cause no new problems of this sort, we'll certainly incorporate them. I think my old plan for the probes was to add some calculation just for the contact lights, to see how close to the ground the probes are. But if it works with touchdown points, that would be an easier solution.

**Comment by jalexb88** [comment]
So I am testing the new touchdown points and it works great for the most part! There is one small issue though and I cant seem to understand why its doing this from the code. When you load a scenario with the LM landed on the moon, it loads fine, but if you use the scenario editor to change the location of the LM on the moon, and the apply it, the LM will spawn up-side down. I remember having that issue when I worked on those TD points before and I had fixed it some how but I cant seem to find the cause with these new TD points. Other then that they are great and if we can just fix that issue I call these a go!

**Comment by ggalfi** [comment]
I think there is a simpler solution for that issue: simply change td[0] and td[1] with each other, instead of my orginal version:
	td[0].pos.x = ro;
	td[0].pos.y = -3.86;
	td[0].pos.z = 0;
	td[1].pos.x = -ro;
	td[1].pos.y = -3.86;
	td[1].pos.z = 0;
you may try this:
	td[1].pos.x = ro;
	td[1].pos.y = -3.86;
	td[1].pos.z = 0;
	td[0].pos.x = -ro;
	td[0].pos.y = -3.86;
	td[0].pos.z = 0;
 I can only guess what is happening: when you move the location of a vessel in scenario editor, it tries to put it down in upright position. And the editor finds the vessel's upright direction by calculating the normal vector of the first three TD points. The normal vector is calculated by the right-hand rule (i.e. if your fingers on your right hand are pointing into the direction of increasing indices of points then your thumb is the normal vector). So exchanging any pair of the first three points will reverse the normal vector. Yesterday I didn't have any clue that the ordering of the TD points matters so I assigned them randomly and the first three was right-left-forward footpad which - by the right-hand rule - resulted in a downward pointing vector. Changing the ordering to left-right-forward will give a correct (upright) normal vector. I tested this trick and now repositioning happens without any acrobatic maneuver, it only sways a bit for a second. Though I'm pretty sure in it, it is just my theory and only someone familiar with the guts of Orbitersim could confirm it.
I think, similarly changing the x-y coordinates will change the direction of the points and resulting in an opposite normal vector. However I don't prefer this solution, because the layout of the probes is not symmetric for x-z change (originally the forward probe is missing, after the change the right one will be missing), so you will get slightly different behaviour for the contact light with this method.

**Comment by ggalfi** [comment]
While I was writing my previous comment I wasn't aware that you have already committed the changes. I've done a rebuild with the most recent version and the contact lights are working perfectly. Even I've done a surface abort and the staging went smoothly without any serious attitude departure. I think we can close this issue. Thank you very much for the very quick action!
