### ISSUE TITLE
Implement LM Suit Fan/Glycol Pump Sounds

### ISSUE THREAD

**Issue by rcflyinghokie** [dseagrav/NASSP#372]
The LM is eerily quiet right now with no system sounds compared to the CM.  Astronauts reported the primary noise in the LM was the glycol pumps.  I believe we can comb through some water pump sounds and find one that fits unless anyone has an idea of what they should sound like (I imagined higher pitched muffled droning?).  

Additionally the suit fans should probably make a little bit of noise when on, something similar to the CM cabin fans, perhaps?

**Comment by schnepe2** [comment]
For the glycol pump I would think that it might have sounded like the pumps used in refrigerators.
[This sound from freesound.org](https://freesound.org/people/Omega9/sounds/267064/) I like, as it has that distinctive startup and (even more distinctive) shutdown sound.
Playing this sound periodically is what I would expect to hear in the LM...

**Comment by jalexb88** [comment]
I have been working on this for the past few days actually and have the glycol pump and suit fan sounds (sound files that rcflyinghokie added) now playing in the simulation. This should be ready for PR shortly!
