### ISSUE TITLE
Apollo 8 MCC - Manuver Pad does not appear

### ISSUE THREAD

**Issue by pikachu1992** [dseagrav/NASSP#376]
I came to inform that I detected a bug in the Apollo project. In the Apollo 8 mission a checklist failure occurs in GET + 1h35. The maneuver pad does not appear in this GET, nor do we have information about the TLI later. This is happening in the last version (1263) for the 2016 orbiter. I also remember that in about 3 months this did not happen in previous versions.

**Comment by indy91** [comment]
I can confirm this problem in the old scenarios that came with the NASSP 7.0 release (and haven't been updated yet for NASSP 8.0). I'll investigate if this is just a problem with old scenarios or more general.

**Comment by indy91** [comment]
The issue should be fixed, the maneuver and the Maneuver PAD for it are calculating correctly again in my old scenario. Does it work now again for you?

**Comment by pikachu1992** [comment]
Hello,

The problem is fixed with NASSP-V8.0-Alpha-Orbiter2016-1264.Manuever pad TLI + 90; TLI + 4 and TLI are already provided on Apollo 8. Thank you very much, good work.
Best regards
