### ISSUE TITLE
Too early TPI by RTCC

### ISSUE THREAD

**Issue by ggalfi** [dseagrav/NASSP#409]
Hi,

I have a minor issue with RTCC's TPI calculation. I am currently going through the MCC-supported A11 mission, and got to the point (at about 122 hours) of the lunar liftoff planning. When I do the concentric rendezvous calculation in RTCC MFD with 124:20:00 as TLO guess I got the following figures (TLO: 124:26:00; TCSI: 125:24:12; TCDHI:126:22:10; TTPI:125:47:14). The first three numbers are seem to be quite plausible, but the time for TPI is apparently wrong as it is well before the CDH burn. The same figures appeared in the MCC-generated ascent PAD. Even with this obviously wrong TPI I executed the ascent at the given TLO. At cutoff I ended up almost right below the CSM, so the liftoff happened far too early and a textbook-like coelliptic rendezvous was impossible. I analyzed the rtcc.cpp to find the cause of this erroneous calculation and I was able to trace it back to the method how the TPI time is fitted to midnight about two and a half after launch. The problem was that the calculation here
`ttoMidnight = OrbMech::sunrise(sv_TPI_guess.R, sv_TPI_guess.V, sv_TPI_guess.MJD, hMoon, hSun, 1, 1, false);`
`res->t_TPI = t_TPI_guess + ttoMidnight;`
have put TPI to the midnight in the **past** of t_TPI_guess=t_L_guess + 2.5 hours. In my scenario the CSM is in a bit higher orbit than planned, so the orbital midnight occuring a few minutes later and it is in the future of  t_TPI_guess. So I ended up with a TPI planned two hours earlier than desired - and accordingly all other numbers (TLO, TCDH) are aligned to this wrong TPI. My correction for the problem was to find a midnight in the past and in the future of t_TPI_guess and to select the closest one:
`		ttoMidnight_p = OrbMech::sunrise(sv_TPI_guess.R, sv_TPI_guess.V, sv_TPI_guess.MJD, hMoon, hSun, 1, 1, false);`
		`ttoMidnight_f = OrbMech::sunrise(sv_TPI_guess.R, sv_TPI_guess.V, sv_TPI_guess.MJD, hMoon, hSun, 1, 1, true);`
		`if (abs(ttoMidnight_f) < abs(ttoMidnight_p))`
			`ttoMidnight = ttoMidnight_f;`
		`else`
			`ttoMidnight = ttoMidnight_p;`
		`res->t_TPI = t_TPI_guess + ttoMidnight;`
With this calculation the new numbers were (TLO: 124:28:37; TCSI: 125:26:48; TCDHI:126:24:46; TTPI:125:47:14) and this plan was quite accuratelly flyable with the normal procedure.
[Apollo 11 Liftoff planning scenarios.zip](https://github.com/dseagrav/NASSP/files/2475638/Apollo.11.Liftoff.planning.scenarios.zip)

**Comment by indy91** [comment]
Looks like it's mainly a problem in the function OrbMech::sunrise itself. The last parameter (bool future) is to enforce a solution that lies in the future versus close to the initial guess time. You seem to have found a rare case where it doesn't find the closest time but for some reason goes a revolution back. I'll have a fix for this soon.

**Comment by ggalfi** [comment]
Hi Niklas,

that commit seems to solve the problem. For my previously attached scenario I get the correct numbers now. Great job, thanks a lot!
