### ISSUE TITLE
Apollo 10 Checklist an Maneuver PAD Possible Issue/Bug

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#423]
Hello

I think  I discovered a problem in the nassp checklist and in the maneuver Pad for separation burn of the CSM after the undoking in apollo 10. I was able to do the undocking of the LEM exactly on GET 98H20, just 10 minutes of the scheduled time, which is very good in apollo 10. The LEM seems to be working very well! Then I got the CSM separation burn in the correct GET. The problem starts here.  The NASSP checklist tells me to do a + 2.5 ft/s translation, as can be seen here:

https://puu.sh/CewlD/8bee8cfb5d.png

https://puu.sh/CgTeI/cf15169845.png

https://puu.sh/CgTg0/02474991c2.jpg

I have already checked the maneuver PAD for CSM separation, all values are correct, attitude, dV, TIG, star check went good (41 in this case). I continued and got to the part where we have to activate the RR in LEM:

https://puu.sh/CgTie/6c2f117885.png

I also activated the transponder in CSM and the P20 Rendezvouz tracking attitude at this time first. Then in the LEM I activated the RR, and I noticed that when I got to the V37E20E, the PNGS calculated a very different attitude from the current one, because the CSM was above the LEM. But I thought it was normal.  After picking up the RR signal, I started having problems in the AGC, the PROG light always on, and when it was time to move from PNGS to AGS mode, the LEM tried to stay in front of the CSM, but always varying, its attitude in an exaggerated way.

https://puu.sh/Cg0WS/03cc7332d3.png

I thought I was doing something wrong, so I've been trying for a while, but always unsuccessful. Yesterday by chance when I was looking at the apollo10 flight plan I notice that the CSM separation burn is a -X  translation  and not + X:

https://puu.sh/Ch2yD/083da7e315.png

and also the attitude of CSM in P20 is quite different in the flight plan, the one I was getting, which was something like:

https://puu.sh/Cg0Tt/5aedd0f0ef.png

and in the flight plan we have
R +00000
P +05500
Y +00000
After the –X

https://puu.sh/CgTso/e324ffde50.png

Very similar.
I tried yesterday to make the separation of the CSM with the same attitude, but with a translation -X 2.5 ft / s. The LEM stayed above the CSM (this is in agreement with the CSM separation burn in Apollo9 where the LEM is also above the CSM), and directly facing it; P20 was in an attitude similar to that of the flight plan, and everything after that began to run smoothly, with no errors in AGC, and at time to switch form PNGS to AGS mode, the attitude looks great, It is only always adjusting the pitch a bit, but it is relatively stable.

https://puu.sh/CgTnE/e288bcc0ef.png

https://puu.sh/CgTna/a64bafe1c7.png

and then I finished operations with RR and P20 without any errors in both LEM and CSM AGC.
So I think that the checklist is wrong in the translation that should be –X. I also think we should load in the EMS -2.5 ft (what I did was a -X translation  until the EMS displayd 5 ft/s) , and the value in the AGC of the CSM should be R1 = -00025. Maybe in the pad the values of dVs that are:

dVx = + 00000
dVy = + 00000
dVz = -00025
Maybe they should be:
dVx = -00000
dVy = -00000
dVz = + 00025

https://puu.sh/CgTeI/cf15169845.png

https://puu.sh/CewlD/8bee8cfb5d.png

Just a guess :) ,  or maybe I'm making a big mistake somewhere! Anyway everything seems to go well if I do -X translation, even in the LEM IMU alignment right after the RR; the LEM puts itself in the right attitude and centered on the star given by the AGC. So I think LEM was well activated before Undocking. Is this a bug? A problem with the PAD?or my mistake?
Just one more question. In the checklist, the message "AGS Attitude Errors Zero", do I have to do anything here?

https://puu.sh/CgTlq/6a43068451.png

Thanks for your time!

**Comment by indy91** [comment]
Yes, the Checklist MFD is definitely wrong. It should be a -X RCS thrusters maneuver, the flight plan confirms that. The DV vector on the Maneuver PAD is essentially right though, because it is a trick for P30/P41. If you give P30 -2.5 ft/s instead of what you actually burn (+2.5 ft/s) in DVZ then P41 can do an auto maneuver to the correct burn attitude with the -X thrusters. Both EMS and DSKY will then end up with 5.0 ft/s residuals, but that is desired and expected. So I think only the checklist needs to be changed.

About the AGS question, I think you are setting up the AGS to steer the LM so that it faces the CSM. That's the normal tracking attitude. And "AGS Attitude Errors Zero" in this context means that you are maneuvering to that attitude so that it faces the CSM. This will also result in the RR having the angles 0/0 when it's locked on to the CSM.

**Comment by RL77** [comment]
Thank you very much again indy91! I going to continue with the mission, and proceed to the DOI burn  :).
