### ISSUE TITLE
Apollo 10 LEM depressurized

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#429]
Hello,

I have a problem in the LEM in the apollo 10 mission. I already did the undocking, the CSM separation burn, the DOI went very well, and I made the next burn just after passing  the orbit perihelion . The LEM works pretty well apparently. When I got close to the first burn after the DOI (GET + - 100h55), I noticed that the LEM was completely depressurized, as you can see here:

https://puu.sh/CiLl6/af5c31e1f4.png

The pressure of the suits is also low. I started loading my previous save files to see where the depressurising had started. It seems that the de-pressurizing of the LEM begins soon after undocking.

Before undocking:

https://puu.sh/CiLaM/afa3872bac.png

2 minutes after undocking:

https://puu.sh/CiLct/be5ba0acf6.png

The O2 and H2O indicators read zero too. I have already confirmed and the depressurizing valve of Foward Hatch, is in Auto, just as the checklist says. Maybe the problem is in Overhead Hatch, in which we still do not have access. Anyway, the LEM continues to work fine, I'm just worried when it's time to dock again, if after that I'll be able to pressurize the LEM again. Is this a bug, or did I do something wrong?

Thanks for your time

**Comment by indy91** [comment]
Of course you have access to the overhead hatch, the panel for it is above the ECS panel.

**Comment by RL77** [comment]
Thanks :D ahahah, my mistake sorry! I thought the way to this hatch was another , above the front panel. And I thought it was not ready yet! 

https://puu.sh/CiZ5J/17b5f3368a.png

On my mission I am shortly after the first burn, after DOI on GET+-101h10. If I set the depressurising valve to Auto at this time, can the LEM be pressurized again? Or should I repeat it all again just before the undocking?

Thanks :)

**Comment by indy91** [comment]
You probably have enough O2 to spare, after all the ECS was planned with multiple EVAs in mind. So no need to start again.

**Comment by RL77** [comment]
Ok that great! Sorry for bothering you! Thank you very much !

**Comment by indy91** [comment]
No problem at all!
