### ISSUE TITLE
Does anyone have a full video tutorial of an apollo missing from start to finish?

### ISSUE THREAD

**Issue by hydrogenpi** [dseagrav/NASSP#441]
I see some on youtube but they aree either of very old versions of NASSP or otherwise just segments of it (tutorial of launch, landing, etc) 

Is there a comprehensive full tutotrial of the entire thing, be it pdf doc or video?

**Comment by indy91** [comment]
No, I don't think there is such a thing. And really, a "comprehensive full tutorial" would be an entire astronaut training course plus everything you need to know about Orbiter and NASSP specifically. There are of course a bunch of good resources:

This video by Bunyap (which you might have already found) that should still for the most part apply to the most recent version of NASSP: https://www.youtube.com/watch?v=CUmANMNbvlo Good video to start finding your way around the spacecraft.

For information on all the subsystems of the CSM and LM you should get the Apollo Operations Handbook for both:
CSM: https://history.nasa.gov/afj/aohindex.html
LM:  https://www.hq.nasa.gov/alsj/LM10HandbookVol1.pdf

We also have a wiki that is a bit out of date: http://nassp.sourceforge.net/ which has articles describing various subsystems in a more comprehensive way than the AOH.

And if you have any specific questions feel free to ask them on the Orbiter Forum or in the NASSP IRC channel (#nassp on freenode).

**Comment by hydrogenpi** [comment]
Thanks
