### ISSUE TITLE
Apollo 11 LEM cockpit Temperature

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#453]
Hello

I finished apollo 11 finally a few days ago :). Thanks for all the help!

https://puu.sh/CErFm/bd1c33e941.jpg

https://puu.sh/CErHz/57c88ac280.jpg

 I just want to report that the temperatures of the cockpit in the LEM continue to reach 100 Fº, but with the difference that the temperature of the space suites is normal, contrary to what happened to me in Apollo 10, but I finished the mission anyway.

https://puu.sh/CDrhz/2cbded0477.png

 After that I tried to finish the apollo 9 (which I gave up) again from the activation of the LEM to the undocking (the temperatures in the LEM are also from 100Fº to Apollo 9). Things went better but they ended up the same way. The LEM does not find the CSM after the first burn. Since I've already done apollo 10 and 11, I noticed that there are two missing uplinks, i think. In apollo 10 and 11,  there are two uplinks before undocking, one for each ship , and another two also for each ship, shortly after the undocking. Apollo 9 has no uplinks for CSM and LEM  shortly after undocking ou later. Dont   we have to do these uplinks in Apollo 9 with ApolloRTCC MFD?

Thanks

**Comment by indy91** [comment]
The cabin temperature could be the fault of the astronauts, if you have them in the cabin and not in the suits and also have a lot of other heat going into the cabin (lights being on for example). That's of course not exactly realistic (the LM ECS definitely still needs work), but what helped me with that is to put the astronauts into the suits for a few hours, with the PAMFD on the ECS page. Then the cabin temperature usually recovers, provided there was no bug that broke the ECS again.

Apollo 9 does some things a bit differently. Which uplinks do you mean though? Which important data would they contain?

**Comment by RL77** [comment]
Ok thanks, I just wanted to report the temperature problem for you to know. The uplinks I think are missing are those occurring soon after undocking on Apollo 10 and 11. The LEM receives the uplink with the state vector of CSM, and CSM the uplink with the state vector of LEM. As this does not happen in Apollo 9, I thought it was because of this that the LEM dosent work prorpely, since I managed to get the LEM to work well in 10 and 11, there should be no reason not to be able to it in apollo 9. I've also seen the manuals, there is a series of codes for  the  AGS that are different  when the LEM flies on Earth.
After the first burn the LEM can not find the CSM in order to activate the RR and count the marks. Here's something you told me on the Orbiter forum at that time:

"'m sure it can be fixed by going back to an earlier save file. The LM pointing at the CSM in P20 mainly depends on two things in the LGC: CSM state vector and LM state vector. The CSM state vector will have been uplinked some time before undocking. Later it has to be updated with P76 so that the LGC knows about the CSM sep burn. The LM state vector was also uplinked some time before undocking and will be unchanged until the phasing maneuver, which the LGC should be monitoring and incorporating the burned DV. If any of these haven't been done or not done properly then the LM of course can't find the CSM. In which case you shouldn't even bother attempting the rendezvous maneuvers, because all the calculations will be wrong."

Here is the link: https://www.orbiter-forum.com/showthread.php?t=40032

Here you say that uplinks appear before, and they do, but in the case of apollo 10 and 11 there is an uplink for each ship before and after the undoking, total of 4 uplinks. So because of this I thought something might be wrong in apollo 9, but of course, things can be different in apollo 9!
Anyway now I'm doing apollo 11 again. Maybe  try 9 when it's over, but I really would like to know if the uplinks in apollo 9 are missing, or why I managed to activate LEM well on apollo 10 and 11 missions, and complete these missions, and why  I cant not do it in apollo 9.

Thanks!

**Comment by indy91** [comment]
Apollo 9 did not have the uplinks directly after undocking. So you need to be careful with state vector preservation, or else you get problems. The flight plan has uplinks/PAD updates there, but the flight plan is outdated. I've read the transcripts and there are no updates there. At least that's how I remember it from when I implemented the Apollo 9 MCC calculations. So it must be some procedural error on your part, or maybe the checklists are not right or so.

**Comment by RL77** [comment]
Ok thanks for now I'll keep training on apollo 11, maybe later  I'll try apollo 9 from the start! Just a question, what do you mean by "preserving the state vector"? how can preserve, or not, preserve the state vector?

**Comment by indy91** [comment]
If you do a burn and don't have the Average G routine running (any of the P4X programs) then the AGC doesn't know about the burn and has a wrong state vector. If the other vehicle does a burn and you don't get an updated SV uplinked or if you haven't used P76 for that then the AGC doesn't properly know anymore where the other vehicle is. That's what I meant with that.

**Comment by RL77** [comment]
Ok thanks for the help indy91!
