### ISSUE TITLE
Fuel Cell purging Alarm

### ISSUE THREAD

**Issue by tcirre93** [dseagrav/NASSP#457]
When performing O2 purging on the fuel cells, no alarm is activated on fuel cells 1 and 2. When purging fuel cell 3 an alarm occurs and the indicators for all 3 fuel cells are lit. I noted that fuel cell temperature falls to minimum when purging Fuel cell 3. H2 purging works as it should for fuel cells 1 and 2. H2 purging on fuel cell 3 is the same as for O2 purging. I have only tested this with Apollo 7.

**Comment by indy91** [comment]
This has been fixed in https://github.com/dseagrav/NASSP/commit/20186b69b577148422f6edce5fe3c20c3e347da7
