### ISSUE TITLE
AGS  does not display  the numbering in initial checklist for take off

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#500]
Hello

I've been doing the Apollo 11, and I landed yesterday. Now I was starting the checklist to take off from the moon. When it was time to test the AGS, the AGS does not show the numbering on the display, although the "ERROR" light works, and seems to light up at the right time if we follow the checklist.

https://puu.sh/DVHZy/d76dee9f17.png  

https://puu.sh/DVHYy/a383a9bcf2.png

 Have also made the initial checklist since T-2h30 for launch three times to verify if I made a mistake, but it still does not work. The AGS cb is closed as in the checklist.

https://puu.sh/DVIa4/781134aaba.png 

However I loaded a save file from an previous mission at about the same GET, and started the checkist at T- 2h30 from launch and AGS works fine. Only in this last mission in particular for some reason it does not work. It's the first time it happens. Could it be a bug? I'm thinking of going back and land again, see if the AGS works later. Can you give me a hand?

Thanks

**Comment by indy91** [comment]
Check your ANUN/NUM rotational switch. If it is set all the way to DIM then the DEDA display won't work. This should also affect mission and event timer, but that might not be properly wired in NASSP yet.

**Comment by indy91** [comment]
Ah wait, that can't be it, the DSKY would also not work.

**Comment by RL77** [comment]
Hello
Ok i going to see that as soon as i can, and i ill report to you. Thanks

**Comment by RL77** [comment]
Ah and this happened in update 1464, but i already instaled 1465. Also i forgot to  report that the S-Band antena got stuck during the checklist after landing. It was the first time it happened to. Thanks

**Comment by indy91** [comment]
In what way did it get stuck? Auto tracking for the steerable antenna isn't implemented yet, so it would just not move in Auto I guess.

And if my suggestions above don't fix the DEDA issue then I'll have to take a look at your scenario to see what is going on.

**Comment by RL77** [comment]
There is in the checklist between the landing and the EVA, a time  that we have to ajust the pich and yaw of the S-Band antenna to pick up the maximum signal strength. Usually if i put the external camera i can see the antena moving as i ajust the pich and yaw of the antenna. This time this did not happen, but may have been me that made some mistake in the checklist.

**Comment by indy91** [comment]
Oh, so it's a possible animation problem. I'll tell jalexb88 about it, he implemented all those animations.

**Comment by RL77** [comment]
Ok thanks i will report as soon i can. If it the DEDA doesnt work, i will send you my save file.

**Comment by RL77** [comment]
Ok thanks i will report as soon i can. If it the DEDA doesnt work, i will send you my save file.

**Comment by RL77** [comment]
Hello
I did the checklist again from T-2h30 until the AGS test. Unfortunately, it looks like there is  a DEDA Bug. The ANUN / NUM rotational switch is at maximum, as are all lights, and the AEA Cb is closed. I did this again just now, updated with today 1466 version. I will send my savefiles through the Orbiter Forum in a minute.

**Comment by indy91** [comment]
I checked your scenario and you have slighly bigger issues than the DEDA not properly working. You have no AC power! The inverter switch is set to inverter 1, but the circuit breaker for it is open. The CB being open at that time is correct, the switch set to 1 instead of 2 is not correct. I checked the Checklist MFD and the "Lunar Stay Switch Positions" checklist definitely has the switch set to 2, instead of 1. I guess you must have missed that. Unless the switch is set to 1 somewhere else in the Checklist MFD by error.

**Comment by RL77** [comment]
Ok thanks, now that you mentioned the inverter, i remember that somewere on the checklist i was wondering if was inverter 1 or 2. So i have to switch to inverter 2 to correct the problem? Did you get the DEDA to work by switching to inverter 2, or is still a problem in addicion to the AC power?In the next mission i will pay atention to the checklist to understand why i was wrong with the inverter.

**Comment by indy91** [comment]
DEDA, mission and event timer all started working when they got AC power. And the Inverter caution light also gets extinguished that way.

**Comment by indy91** [comment]
Normally you operate on inverter 2, with the inverter 1 circuit breaker opened. For redundancy you close the INV 1 CB and switch to inverter 1 for the powered descent. And then some time after landing you would go back to the previous configuration with only inverter 2 operating. That is probably the point where the error happened.

**Comment by RL77** [comment]
Ok thank you very much for this lesson, it was my mistake no doubt, sorry for the inconvenience. Next misson i will pay attention to this. By now a want  to start reading the teory of the CSM, LM, AGC and AGS. The manual for the AGC and AGS i already have, and some others... wath is the manual you recommend for the CSM and LM in general?

**Comment by indy91** [comment]
No problem! The best resource is the Apollo Operations Handbook. Volume I has detailed systems descriptions, Volume II all the procedures. It is available for both CSM and LM.

**Comment by RL77** [comment]
Ok thanks indy91!
