### ISSUE TITLE
ECSIndicatorsSwitch bug

### ISSUE THREAD

**Issue by mmontour** [dseagrav/NASSP#501]
There's an issue with the ECS INDICATORS switch on the CSM main panel in the current "Orbiter2016" branch. When it's in the PRIM (left) position many of the gauges show data from the secondary glycol loop, and conversely SEC (right) shows the primary loop.

In src_csm/saturnpanel.cpp:
```
	ECSIndicatorsSwitch.AddPosition(0, 340);
	ECSIndicatorsSwitch.AddPosition(1, 20);
	ECSIndicatorsSwitch.Register(PSH, "ECSIndicatorsSwitch", 0);

```
In src_csm/satswitches.cpp the inlet temperature is correct:
```
double SaturnEcsRadTempInletMeter::QueryValue()
{
	if (ECSIndicatorsSwitch->GetState() == 0) {
		return Sat->PriRadInTempSensor.Voltage()*13.0 + 55.0;
	} else {
		return Sat->SecRadInTempSensor.Voltage()*13.0 + 55.0;
	}
}
```

However the logic is reversed for the evaporator outlet temperature:
```
double SaturnGlyEvapTempOutletMeter::QueryValue()
{
	if (ECSIndicatorsSwitch->GetState() == 1) {
		return Sat->GlyEvapOutTempSensor.Voltage()*10.0 + 25.0;
	} else {
		return Sat->SecEvapOutLiqTempSensor.Voltage()*10.0 + 25.0;
	}
}

```

Also affected: SaturnGlyEvapSteamPressMeter::QueryValue(), SaturnGlycolDischPressMeter::QueryValue(), SaturnAccumQuantityMeter::QueryValue().

This can be seen in e.g. the Apollo 11 "After Insertion Checklist T+1h" scenario by switching between the PRIM and SEC display modes and watching how the gauges react to switching the cooling pumps and evaporators on and off.

**Comment by indy91** [comment]
Probably got broken with pull request #468, Alex also changed all the rotational switches to be consistent and start with position 0, instead of 0 or 1 randomly. Should be an easy fix. Thanks!

**Comment by indy91** [comment]
This has been fixed. Can you confirm that?

**Comment by mmontour** [comment]
Thanks, I confirm that this has been fixed. Should I also close the issue or will you do that?

**Comment by indy91** [comment]
Consider it done!
