### ISSUE TITLE
PriRadInTempSensor wiring

### ISSUE THREAD

**Issue by mmontour** [dseagrav/NASSP#502]
When the ECS RADIATORS HEATER PRIM switch is in its center-off position, the ECS RAD TEMP INLET meter on the Primary loop (ECS INDICATORS = PRIM) reads off-scale low. If either the PRIM 1 or PRIM 2 heater is selected then the temperature meter shows a reading.

In satsystems.cpp:

`	PriRadInTempSensor.Init(&EcsRadiatorsHeaterPrimSwitch, (h_Tank *)Panelsdk.GetPointerByString("HYDRAULIC:PRIMRADIATORINLET"));
`

While the gauge circuit is physically wired to this switch, it is electrically fed from an upstream MNB circuit breaker regardless of the toggle switch position (including the center-off position). So I think this line should be:

`	PriRadInTempSensor.Init(&CONTHTRSMnBCircuitBraker, (h_Tank *)Panelsdk.GetPointerByString("HYDRAULIC:PRIMRADIATORINLET"));
`

**Comment by indy91** [comment]
You are right, I interpreted the Systems Handbook wrong when I implemented this sensor (mostly for telemetry). As the AOH says:

> CB70 supplies power to primary inlet temperature sensor through HEATER-PRIM switch in all positions.

 I also changed the EcsRadiatorsHeaterPrimSwitch entirely unnecessarily. I'll fix this soon!
