### ISSUE TITLE
LM Panel 2 CW lights ("caution" lights) should all be yellow

### ISSUE THREAD

**Issue by rcflyinghokie** [dseagrav/NASSP#666]
Based on the AOH, Systems Handbooks, and functional diagrams, it appears the LM CW lights on Panel 2 should all be aviation yellow as opposed to matrix 3 being yellow and matrix 4 being white. I have attached excerpts as evidence.

![4](https://user-images.githubusercontent.com/22916885/146231611-879518b4-03c5-471b-813b-d5b8f4f8a737.png)
![3](https://user-images.githubusercontent.com/22916885/146231616-c29f77b8-8efd-42f6-959c-f1f596d7f1d8.png)
![2](https://user-images.githubusercontent.com/22916885/146231630-0ce255db-a688-4c3f-92a9-684658725b25.png)
![1](https://user-images.githubusercontent.com/22916885/146231638-db283a8f-e719-4bee-a5c8-fd0217f64f2f.png)

**Comment by ThymoNL** [comment]
Resolved by #667
