### ISSUE TITLE
Add SPS FLANGE TEMP light and circuitry to pre Apollo 12 CM's

### ISSUE THREAD

**Issue by rcflyinghokie** [dseagrav/NASSP#705]
As was pointed out on the forums, Apollo SC before Apollo 12 had the SPS FLANGE TEMP light on the CW panel. Since we are supporting 7-11 right now, I think it would be prudent to add this CW light to those panels, if possible specifically for just those missions.

**Comment by n7275** [comment]
@Jordan-64 While you're working on CM VC stuff, would it be possible to add a "SPS FLANGE TEMP" Light as seen here: 
![image](https://user-images.githubusercontent.com/100335/218641708-b3373b9d-54d4-4eed-be39-6cb1066669bc.png)

**Comment by indy91** [comment]
Fixed by #945
