### ISSUE TITLE
Apollo 11 checklist typos

### ISSUE THREAD

**Issue by jumpjack** [dseagrav/NASSP#718]
I think there are some typos here: https://github.com/orbiternassp/NASSP/blob/Orbiter2016/Doc/Project%20Apollo%20-%20NASSP/Checklists/Apollo%2011%20Checklists.xls

![immagine](https://user-images.githubusercontent.com/1620953/155154945-d2c980fd-5c9d-44a9-9520-f965eda3f356.png)

1) Stranded "2" in TIME and PANEL columns?
2) "SYS A QUAD" should be "THRUSTER PAIR ISOL VLV" (unless you found the documents which maps "thrusters pair" text to "SYS QUAD" control, I am still looking for it... :-( )
3) All "SYS A QUAD" should be set to OPEN, not to ENABLE
4) "MAIN SOV (2) - OPEN" is missing ("open both shut off valves")
5) CRSFD - CLOSE is missing (CROSSFEED)

I found a cool document, which lists and maps all controls of CSM: http://history.nasa.gov/afj/aoh/aoh-v1-3-cont+disp.pdf

Unfortunately I cannot find such a document for LM, so I built a page which should allow compiling such a document, but they're around 2 hundreds of controls to type by hand. In case anybody wants to help...:

https://jumpjack.github.io/Apollo11LEMdata/image-mapper.html (please wait until a big image loads)

You have just to click on a control, type its name in the "label" field, and optionally type the number of the panel, the type of control (circuit breaker, switch,...) and any needed comment, then click SAVE: it will add a JSON-formatted line to the output. "FREE" unfreeze the zoomed area.

The resulting list (which must be manually pasted into a JSON file) will be the input for another page which highlights the right quadrant in the image, given the name of the control; it could be useful for tutorials of orbiter simulator.

But in case anybody wants to help, we should coordinate the job, to avoid same person working on same panels.

**Comment by rcflyinghokie** [comment]
> "SYS A QUAD" should be "THRUSTER PAIR ISOL VLV" (unless you found the documents which maps "thrusters pair" text to "SYS QUAD" control, I am still looking for it... :-( )

> All "SYS A QUAD" should be set to OPEN, not to ENABLE

So interesting thing, these actually were named different things in different procedures. If you look at the LM activation checklist or surface checklists you will see SYS A QUAD etc. And if you look at later missions, all it says is "Recycle Parker Valves."

I have no issues relabeling these with a heading that states that but just bear in mind this sort of thing changed. Also the individual switches are more easily labeled as they stand. I will have a PR up with these fixes shortly.
