### ISSUE TITLE
Add checklists/MCC data for Apollo 12

### ISSUE THREAD

**Issue by CaptainSwag101** [dseagrav/NASSP#752]
Since we have quite a few mission documents from later Apollo missions, I think we should begin adding checklist MFD and MCC support for these missions, starting with Apollo 12. This is a good mission to begin with as it probably bears the most similarities in terms of procedures and structure with the already-implemented Apollo 11. Therefore it should take relatively little extra effort to implement, since we can start from that mission's data as a base.

I know how to create the MFD checklist for this mission and set it up for the default SCN, but I will require help for finding and preparing the scripted MCC PAD data and uplinks.

**Comment by indy91** [comment]
The long term plan for NASSP 8 has always been to fully support Apollo 7-11 minus a detailed EVA simulation. You are right that Apollo 12 is quite similar to 11 and if I was going to start work on the MCC for Apollo 12 it would be a simple copy & paste from Apollo 11 as a start.

I recently flew Apollo 12 and my idea was rather to have a detailed walkthrough of Apollo 12 using the RTCC MFD. It can be a lot of work to keep the MCC up-to-date with RTCC updates, so adding more missions right now might not be the best of ideas. Implementing checklists right now of course would be great as the procedures shouldn't change too much with NASSP updates, but with the MCC there is always an inherent workload when any RTCC update is done that applies to all missions. There is always something in the MCC that needs to be updated then for all supported missions.

**Comment by maxq519** [comment]
I like the approach of using RTCC with a step-by-step walkthrough and accurate checklists.  It would also act as a sort of “RTCC Training” mission.

**Comment by jalexb88** [comment]
I have created a branch with Apollo 12 MCC tracking here: https://github.com/jalexb88/NASSP/tree/MCCApollo12
As of now it is working up to LOI-2 and I am progressing forward. Beware there could be many bugs, this is more of an experiment on my part to see if I could program an MCC mission myself. This will not be fully supported for a NASSP 8 release (as stated Apollo 7-11), and if eventually merged into the main branch will be a WIP "bonus" MCC tracking mission.

**Comment by jalexb88** [comment]
#850

**Comment by maxq519** [comment]
Any plans to create the flightplan for Checklist MFD?

**Comment by jalexb88** [comment]
> Any plans to create the flightplan for Checklist MFD?

Ryan (Folgers) is usually the expert on checklist MFD matters, I think he showed some interest in making them for 12 eventually, but it may not be for a while.

**Comment by maxq519** [comment]
> > Any plans to create the flightplan for Checklist MFD?
> 
> Ryan (Folgers) is usually the expert on checklist MFD matters, I think he showed some interest in making them for 12 eventually, but it may not be for a while.

In the meantime, it is a good practice mission for later flights with no MCC.
We get to practice using real flightplans with MCC support.

**Comment by rcflyinghokie** [comment]
Just updating this, I am about half way through the Apollo 12 checklists. MCC will need things added after the fact as there are many missing updates.

**Comment by rcflyinghokie** [comment]
#979

**Comment by rcflyinghokie** [comment]
Scenario, Checklists, and MCC added with merging of #979
