### ISSUE TITLE
CSM Exterior Lighting Implementation

### ISSUE THREAD

**Issue by rcflyinghokie** [dseagrav/NASSP#776]
The CSM still needs operational exterior lighting. Right now it just has fixed running lights. Systems that need to be added are as follows:

-Running/EVA lights: These are the red/green/amber lights around the spacecraft for orientation. This also includes the EVA floodlight which is boom mounted. This boom deploys during BPC jettison and remains out the whole flight. Powered by the RUN/EVA/TGT AC cbs and RUN/EVA switch.

-Docking spotlight: This light is in a spring loaded compartment behind the LH rendezvous window and provides forward facing light for docking. It is held in the compartment and flush with the SM skin until first use where it springs open and remains open the rest of the flight. Powered by the RUN/EVA/TGT AC2 cb and COAS/TUNNEL/RNDZ/SPOT MNB cb and the EXT LIGHTS RNDZ SPOT switch in SPOT.

-Rendezvous beacon: This light is right next to the CSM umbilical and is canted out 60 degrees in a fixed housing. It provides visibility at 160 nm in the telescope and 60nm unaided and flashes 1 flash per second like the LM tracking light. Powered by the COAS/TUNNEL/RNDZ/SPOT MNA cb and the EXT LIGHTS RNDZ SPOT switch in RNDZ.

-Optionally we could also add fixed lighting in RL EVA handrails. These were located on the docking ring and handles around the spacecraft.

![image](https://user-images.githubusercontent.com/22916885/167152314-b219b4ec-583f-4241-818f-242064c3e2a6.png)

**Comment by n7275** [comment]
I started a branch for this. I don't think it will be too hard.
