### ISSUE TITLE
Running systems simulation on the first timestep prevents liftoff events of Saturn1B in certain mission scenarios

### ISSUE THREAD

**Issue by ThatRedMelon** [dseagrav/NASSP#806]
Due to pull #799, in the scenario `Apollo - Mission Scenarios\Apollo 7\Apollo 7 - 01 - Before Launch T-60s.scn`, no engines light and no liftoff events occur, although this does not happen when using the T-4hr scenario.

The problem seems to arise here:
https://github.com/orbiternassp/NASSP/blob/3e875b576788c3fc77efc175a64eca7fbd1a41b1/Orbitersdk/samples/ProjectApollo/src_saturn/Saturn1b.cpp#L260-L263

Readding the `return;` line at the end of the above code (as seen below, taken from the commit before #799 was merged), hence preventing simulations running on the first timestep, fixes the issue.

https://github.com/orbiternassp/NASSP/blob/739527af066eefed531772e94c7931c40887f6a0/Orbitersdk/samples/ProjectApollo/src_saturn/Saturn1b.cpp#L268-L272

**Comment by indy91** [comment]
Ah, I would have been surprised if there really were zero side effects from this update. Should be easy to find, hopefully also easy to fix. Probably some race condition leading to a launch inhibit signal. I can fix it tonight.

**Comment by indy91** [comment]
Fixed by PR #807
