### ISSUE TITLE
Esystems: diode initialization issue

### ISSUE THREAD

**Issue by TheGondos** [dseagrav/NASSP#831]
Got a random divide by zero error in Diode constructor :
`Volts = SRC->Voltage() - (kT_q*log((Amperes / Is) + 1));`
kT_q and Is are initialized just after this expression.
I did not analyze the issue in depth and suspect a [quick fix](https://github.com/TheGondos/NASSP/commit/5271d5afb3032772607a63b54406af79cb05fb97) should be enough.

**Comment by rcflyinghokie** [comment]
@n7275 can you take a look?
