### ISSUE TITLE
[VC][CSM]Calibrate H2 and O2 pressure indicators

### ISSUE THREAD

**Issue by TurryBoeing** [dseagrav/NASSP#861]
On the VC, the pressure gauges for H2 and O2 don´t match the 2D needle positions/values.
![cryo press issue 1](https://user-images.githubusercontent.com/7021346/197855215-5f6410f1-6529-453f-ac43-27da4beb000a.png)
![cryo press issue 2](https://user-images.githubusercontent.com/7021346/197855237-c8576c15-912d-4b06-9766-42c3c4c3f757.png)

**Comment by n7275** [comment]
@indy91, this can be closed right?

**Comment by indy91** [comment]
@n7275 Yes, @TurryBoeing confirms it is fixed now.
