### ISSUE TITLE
[VC][CSM]EVAP H2O valves are reversed

### ISSUE THREAD

**Issue by TurryBoeing** [dseagrav/NASSP#866]
Between the 2D panel and VC, knobs for EVAP WATER CONTROL on panel 382 are reversed. On the 2D, Primary is on the "Right", but on the VC, Secondary is on the "Right".
![2d_evap_h2o_reversed](https://user-images.githubusercontent.com/7021346/197857326-d74ff0b5-4c53-426e-8a03-92a77135f5f4.png)
![vc_evap_h2o_reversed](https://user-images.githubusercontent.com/7021346/197857332-78b5705d-435a-4ded-84ee-d0c2b685f4f0.png)

**Comment by rcflyinghokie** [comment]
Was this fixed to the point that we can close the issue?

**Comment by indy91** [comment]
Yes!
