### ISSUE TITLE
CSM CW Panel Incorrect Text for CO2 PP

### ISSUE THREAD

**Issue by rcflyinghokie** [dseagrav/NASSP#878]
NASSP uses "CO2 PRESS" as the CW lamp text for high CO2 PP. However, in digging through documents, it appears all of the CM's flew a CW light with the text "CO2 PP HI"

I am not sure where "CO2 PRESS" came from but it seems to be incorrect. Thanks @Jordan-64 for identifying this discrepancy!

**Comment by indy91** [comment]
Fixed by #945
