### ISSUE TITLE
Cue Card Disappearance 

### ISSUE THREAD

**Issue by ThatRedMelon** [dseagrav/NASSP#987]
Certain staging events such as CSM/SM staging, apex cover jettison and parachute deployment cause all cue cards to disappear unless they are reselected, in which case the next cue card that shows up will be the card next in the cycle than what was previously displayed.

Video from pad abort:

https://github.com/orbiternassp/NASSP/assets/34657891/e5fcce7c-8875-4e6e-a710-0169cf3090d5

**Comment by indy91** [comment]
Should be fixed by #1046

**Comment by maxq519** [comment]
I can confirm that this is now fixed, I also checked for the issue during apex cover jettison and the parachute sequence.
I'm going to go ahead and close this, it can be re-opened if needed.
